### ISSUE TITLE
Style improvements

### ISSUE THREAD

**Issue by kresimir-coko** [liferay-frontend/lug-bot-app#20]
Hey @bryceosterhaus I respect your desire to stick with the default Lexicon/Clay styles but I think that we can improve some styles while maintaining the basics. We can use this issue as a discussion to track the things we want to do and not want to do without spending much time implementing them and suffering from the async feedback loop.

**Comment by kresimir-coko** [comment]
## Spacing in the job list items is too big personally

Apart from the spacing, I'd throw in an `align-items: center` on the `panel-header` so that the issue issue name and the `Stage Change` button are vertically aligned.

![image](https://user-images.githubusercontent.com/24564752/123421541-42bab680-d5bd-11eb-8d9b-4769e2f61b72.png)

**Comment by bryceosterhaus** [comment]
That seems fine to me to align the header and button. I would try to use Clay components for that as much as possible, and if it isn't possible with Clay components, make an issue on the Clay repo. If you think it might take more than 20min to figure out the style for that, I would just leave for the team to address in the future. I would try to focus as much time as getting features on the page and then worry about specific styling later since that can be addressed by their team in the future.

**Comment by kresimir-coko** [comment]
> worry about specific styling later since that can be addressed by their team in the future.

You're right. I just discovered that the vertical alignment issue is app-wide, meaning it also happens on components other than that panel header. Can be seen on these Cards that should have the title vertically centered but they obviously aren't


![image](https://user-images.githubusercontent.com/24564752/123601754-51d97880-d7f8-11eb-8185-467b09c59d5c.png)
